trigger:
  branches:
    include:
      - main
  paths:
    include:
      - WebApp/*

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet publish WebApp/WebApp.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish
  displayName: 'Compilation et Publication .NET'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
    ArtifactName: 'webAppArtifact'
    publishLocation: 'Container'

- script: |
    echo "Récupération des fichiers compilés et déploiement sur la VM Linux..."
  displayName: 'Déploiement sur la machine cible'
